### ISSUE TITLE
Locate the owner method of a target API and get the path from the entrypoint to the owner method

### ISSUE THREAD

**Issue by bj3680** [arguslab/Argus-SAF#16]
Hi, first of all, thank you for providing this great framework.

Now, I want to find all paths from the component entrypoints to methods that have a specific API (let's say, for example, Socket.accept()).

To achieve,
I constructed ICFGs for all components in the APK and found the owner methods of the targeted API.
Then, I went backward from the owner methods to the entrypoint.
However, this way took me too much time.
Since we cannot know which components in an app are going to eventually call the owner methods without ICFGs, it is impossible to customize entrypoints.

So, I was looking Argus-SAF code if there exists any available method and found an object implementation, named BackwardCallChain. However, It seems not working properly.

Could you give me some advice how to use it. (or other ways would be also great!)

**Comment by fgwei** [comment]
Yeah, the BackwardCallChain is little old and out of support.
The easiest way to do entry point filtering is to:
1. Do the reachability first: 
https://github.com/arguslab/Argus-SAF/blob/8cf43ddc97c369e661b0683881db6ab2620b3905/org.argus.jawa/src/main/scala/org/argus/jawa/alir/reachability/ReachabilityAnalysis.scala
2. Check whether your interested api is present in the reachable set.
3. If reaches, do more heavy data flow analysis.

**Comment by bj3680** [comment]
Thanks for your quick reply.

I tried it, and it worked for simple cases.

However, I found that the methods called after AsyncTask are not shown in the reachable set.

![1](https://user-images.githubusercontent.com/5917613/28077350-82bdef5c-669c-11e7-8b27-149a660bb923.png)

As an example, I can find the above flow when using idfg.icfg, which means my target API is actually reachable from the entrypoint.

But, the calls from run to writeInstallationFile are not present in the reachable set.

If you can give me a solution for such case, I would be very appreciated.

Thanks!

**Comment by fgwei** [comment]
You are right, the light-weight reachability analysis cannot resolve the indirect calls like AsyncTask. Because this requires points to information to identify corresponding AsyncTask implementation to invoke.
Possible solutions:
1. Add a heuristic indirect call solver to the reachability to guess the possible indirect call types. (I might add it for the next release.)
2. You can do a reachablity from all the AsyncTask functions. If any of them reaches your interested api, then consider any component reaches AsyncTask.execute() call as interesting entry point.

**Comment by bj3680** [comment]
Thank you for the insight. I think the solutions2 is the best option for me now.
